# Generated by Django 5.0.3 on 2024-03-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightinput',
            name='activity_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weightinput',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weightinput',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='weightinput',
            name='height_cm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weightinput',
            name='weight_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightinput',
            name='current_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightinput',
            name='goal',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='weightinput',
            name='strategy',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='weightinput',
            name='target_weight',
            field=models.FloatField(default=0),
        ),
    ]
